### PR TITLE
Warn instead of fail when keychain is unreachable

### LINKED ISSUE #55: Unwanted Dashlane CLI keychain passwords on MacOS
Hello,

after doing some auth tests with the CLI, I found out that for each connexion attempt, the CLI creates a certificate. Maybe moving the creation of this certificate after the user is connected could be a nice feature.

test

### PR DESCRIPTION
**Pull request by jboillot**
Warn the user the keychain is unreachable instead of raising an error.

- When the master password is set for the first time (the DB was absent) or configured to be remembered (`dcli configure save-master-password true`), this will disable the master password (encrypted using the local key) save in the DB (that is then useless because the local key can only be retrieved from the master password). A warning is displayed, so the user can retry using the keychain.
- When the keychain suddenly starts to fail (`save-master-password` set to `true` but `getLocalKey()` returns an error) or the master password encrypted using the local key is absent from the DB, then the keychain is not disabled, but a warning is displayed, so the user knows what is happening and how to disable the keychain.

Because the keychain unavailability does not trigger errors anymore, it has been possible to postpone its access. Thus, this PR resolves #55.

If you think of better warnings, don't hesitate to edit them!

### CODE REVIEW

File: src/crypto/keychainManager.ts [hunk 1]
```diff
@@ -115,6 +101,21 @@ const getSecretsWithoutDB = async (
...
 
+    if (!shouldNotSaveMasterPassword) {
+        try {
+            setLocalKey(login, localKey);
+        } catch (error) {
+            let errorMessage = 'unknown error';
+            if (error instanceof Error) {
+                errorMessage = error.message;
+            }
+            winston.warn(`Unable to reach OS keychain because of error: ${errorMessage}, so its use has been disabled. \
```
Comment (Mikescops) [inline src/crypto/keychainManager.ts:112]:
```suggestion
            winston.warn(`Unable to reach OS keychain because of error: "${errorMessage}", so its use has been disabled. \
```

File: src/middleware/configure.ts [hunk 2]
```diff
@@ -41,8 +42,21 @@ export const configureSaveMasterPassword = (params: ConfigureSaveMasterPassword)
         // Set encrypted master password in the DB
         masterPasswordEncrypted = encryptAES(secrets.localKey, Buffer.from(secrets.masterPassword));
 
-        // Set local key in the OS keychain
-        setLocalKey(secrets.login, shouldNotSaveMasterPassword, secrets.localKey);
+        if (!shouldNotSaveMasterPassword) {
```
Comment (Mikescops) [inline src/middleware/configure.ts:45]: you wrote this twice can you put it in a function to factorise

**Review by Mikescops — APPROVED** [review]
